[package]
name = "dicom-rs-transformer"
version = "0.1.0"
edition = "2021"
authors = ["Manabu Tokunaga"]
license = "Apache-2.0"
description = "A utility library and line-by-line CLI console for transforming DICOM object datasets using JSON-encoded DSL rules."
readme = "README.md"

[lib]
name = "dicom_rs_transformer"
path = "src/lib.rs"

[[bin]]
name = "dicom-transformer"
path = "src/main.rs"

[dependencies]
dicom-object = "0.10"
dicom-dictionary-std = "0.10"
dicom-core = "0.10"
dicom-transfer-syntax-registry = "0.10"
dicom-pixeldata = { version = "0.10", features = ["image"] }
dicom-json = "0.10"
dicom-dump = "0.10"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
rand = "0.8"
chrono = "0.4"
uuid = { version = "1.6", features = ["v4", "v5"] }
bytes = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
clap = { version = "4.4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
tempfile = "3.8"
